host: 127.0.0.1
log:
  logLevel: DEBUG
  logFile:
    Filename: cleat.log
    MaxSize: 10
    MaxBackups: 10
    MaxAge: 30
    Compress: false

windows:
  event:
    eventname:
      - Application
      - System
      - Security
      - Setup

files:
  paths:
    - path:
      charset: GB2312
    - path:
      charset: GBK

output:
  udp:
    serverIP: 127.0.0.1
    serverPort: 514